### ISSUE TITLE
Data Persistence Layer: Decouple & Improve Test Coverage 

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#268]
- [x] add unit tests #257
- [x] migrate to objection.js #247 
- [x] cover all models in tests #278
- [x] integrate jest tests #295 
- [x] refactor id attributes #361 
- [x] refactor services #316
- [x] require -> import #316
- [x] add test coverage report #371

**Comment by sk91** [comment]
#257 
#247 
#277
