### ISSUE TITLE
Implement: Local Error Log with Logfile Export

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#269]
Local log should support:

- Multiple log levels
- The ability to specify a log level via environment variable or command line argument
- The ability to export to a text file via a menu item in the application menu bar
- Mark start point for issue reproduction via menu item

Progress:

- [x] Select and integrate logging library (is electron-log good enough?) #281 
- [x] Define log format #281 
- [x] Configure log levels via env vars #281 
- [x] use the new logger in all codebase #291 
- [x] Add option to export log file #301 
- [x] Mark issue for reproduction #293 
- [x] Add option to change to debug log levels on demand #301 
- [x] integrate with sentry #301

**Comment by sk91** [comment]
> Mark start point for issue reproduction via menu

@dfcowel what do you mean by that?

**Comment by sk91** [comment]
> Mark start point for issue reproduction via menu

@dfcowell what do you mean by that?

**Comment by dfcowell** [comment]
Sorry @sk91 I missed that.

Log files (especially very detailed ones) can get very long.

If we are communicating with a user and they send through a log file it can be time consuming trying to find the relevant part of the file.

Allowing the user to "mark" the file means giving them a menu option that when selected logs a distinctive message to the file like "SUPPORT: ISSUE REPRODUCTION STARTS HERE"

Imagine the case where a user says that they are having trouble adding a token to their wallet. Support will ask them to start the wallet, unlock it, then use the "Help > Mark log file" option before trying to add the token that isn't working.

That lets the developer jump immediately to the point in the log that has the information specifically referring to the problem.

**Comment by sk91** [comment]
@dfcowell @rodrigopavezi I propose that we also play with log level while marking the log file.

There is no sense in bloating the log file with `info` level events by default. I think it should always be `warn`. 

But when the user clicks on `Mark log file` we should switch it to `info` to get more details

**Comment by rhdelima** [comment]
Passed QA

**Comment by itsmeterrylin** [comment]
Closing issue as passed QA.
