### ISSUE TITLE
fix tests for all platforms

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#368]
- [x] fix disabled unit tests on mac #371
- [x] fix unit tests on windows #378 
- [x] fix e2e tests on windows #378 
- [x] fix unit tests on linux #378 
- [x] fix e2etests on linux #378 
- [x] fix sporadic unit test failure
