### ISSUE TITLE
UI Audit: Tweaks & Improvements

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#375]
**Overview: General UI Fixes & Improvements:**
Oana has reviewed the entire application and we have some easy fixes to improve the current UI.

**Task List:**
- [x] Home Screen: Blockchain Identity Wallet - font not loading https://gyazo.com/241ebcf248160a3a7ddd0c4b1a95eb2f Font needs to be Roboto Mono 18px
- [x] Import Wallet: Private Key field should be centered >> https://cl.ly/1l2v2I02110h
- [x] Import Wallet: Close button is barely visible https://gyazo.com/66a270008436af47446abd26fbc7e190
- [x] Dashboard: Copy address button text is not vertically centered https://gyazo.com/82064edf1577aa18a1dcdd8158905f4a
- [x] Dashboard: Crypto chart donut background not loading for 0 value https://gyazo.com/dbe48776d8afbaaa38fe8c46ec95f66d
- [x] Dashboard: Icon colors for actions are different https://gyazo.com/9a58f73f6b623ec0261e7cce2f91f74b We shoud use same color for all 3 icons, correct color is #768FA9
- [x] Import Wallet: Inconsistent button sizes: Unlock in Private Key vs Connect to Ledger. We should keep same width
- [x] ERC-20 Tokens: Disable/Enable Eye and Eye/Slash as trigger for disable/enable change to white color
- [x] ERC-20: Invalid contract error message in top right corner and hard to see
- [x] ERC-20: Fix tool tip display https://mattermost.kyc-chain.com/files/68rks8rzy3fn3xn97acdigycew/public?h=mrAt9pAzn9Ein9IvPDaYD4xbztKouJ-vXVaKUXFNqm8
- [x] SelfKey ID: Add document Input is missing placeholder https://gyazo.com/3010ab97a0becc04903f5c776830debe 
- [x] SelfKey ID: Edit Attribute input labels font size is too small and the required indicator (asterisk) is not visible https://gyazo.com/af8abb256cc116c1c069dd31fe37f52c 
- [x] SelfKey ID: Hover and display "Edit" when over profile photo
- [x] SefKey ID: Upload Document: Missing ? when document is not uploaded yet https://cl.ly/0o0k2b181M0s & https://cl.ly/2L093P3J0s3l
- [x] SelfKey ID: Wrong Font -  https://gyazo.com/efd20c0d8361c264f113590110a1231d 
- [x] Transaction History: Update UI for text, icons, and display: https://projects.invisionapp.com/d/main#/console/15222689/316491951/preview
