### ISSUE TITLE
Implement HD wallet

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#457]
https://medium.com/bitcraft/so-you-want-to-build-an-ethereum-hd-wallet-cb2b7d7e4998

**Comment by sk91** [comment]
- [x] implement ui #2468 
- [x] implement hd wallet service #2471 
- [x] implement unlock flow #2472
- [x] implement create wallet flow #2576
- [] store unlocked wallet in known wallets

**Comment by sk91** [comment]
for QA:

- test new create wallet flow
- test new unlock with seed flow
- see that the address you choose to use from create flow is added to "Existing Addresses" and you can unlock it with passoword
- see that if you unlock previously created address via the seed phrase unlock option, it opens the same wallet (with same identity attributes)

**Comment by rhdelima** [comment]
Looks good. Pass
